{{- if .Values.jupyterhub.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gaffer-jhub.fullname" . }}-jhub
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gaffer-jhub.fullname" . }}-jhub
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
subjects:
- kind: ServiceAccount
  name: hub
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gaffer-jhub.fullname" . }}-jhub
{{- end }}
