apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyterhub.custom.optionsServerServiceName }}
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: options-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "gaffer-jhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: options-server
