{{- if .Values.optionsServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gaffer-jhub.optionsServerServiceAccountName" . }}
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: options-server
  {{- with .Values.optionsServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
