name: Continuous Integration

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@v4
      with:
        remove-dotnet: 'true'
        overprovision-lvm: 'true'

    - uses: actions/checkout@v2

    - name: Install Kubernetes
      run: ./cd/before_install.sh

    - name: Build Images
      run: ./cd/build_images.sh

    - name: Install subcharts
      run: ./cd/install_dependencies.sh

    - name: Lint charts
      run: ./cd/lint_charts.sh

    - name: Deploy to Kubernetes
      run: ./cd/deploy_to_kind.sh
  
    - name: Run gaffer-road-traffic Tests
      run: helm test gaffer || (kubectl get po && kubectl describe po && kubectl logs -l app.kubernetes.io/component=test --tail=-1 && df -h && false)

    - name: Run gaffer-jhub Tests
      run: helm test jhub || (kubectl get po && kubectl describe po && kubectl logs -l app.kubernetes.io/component=test --tail=-1 && df -h && false)
